# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

# options:
#   log_level: debug

shared:
  domain: lan.dev
  registry_pvc_size: 50Gi
variables:
  core-monitoring:
    grafana_ha: true
    grafana_pg_host: pg-cluster.postgres.svc.cluster.local
    grafana_pg_port: 5432
    grafana_pg_database: grafanadb
    grafana_pg_user: grafana.grafana
    grafana_pg_ssl_mode: require
  core-identity-authorization:
    # Keycloak variables
    keycloak_ha: false
    keycloak_pg_username: postgres
    keycloak_pg_password: password
    keycloak_pg_database: keycloak
    keycloak_pg_host: host.k3d.internal
    keycloak_devmode: false
