# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-cert-test
  namespace: istio-system
spec:
  isCA: true
  commonName: bigbang-istio-gateway
  secretName: admin-cert-test
  secretTemplate:
    labels:
      app.kubernetes.io/istio-gateway-secret: admin
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
