apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: intermediate-ca-dev
  namespace: cert-manager
spec:
  isCA: true
  commonName: "Homelab Intermediate CA Dev"
  secretName: intermediate-ca-dev-secret
  duration: 43800h # 5 years
  subject:
    organizations:
      - "Homelab PKI"
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: root-ca-dev-issuer # Must match the issuer name above
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - cert sign
    - crl sign
    - server auth
    - client auth
